version: '3'

services:
  # Application

  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5433'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=nanotech
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis_password_development
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  redis_data:
    driver: local
  postgresql_data:
    driver: local
